branches:
  only:
    - master
language: go
install:
- go get -v github.com/spf13/hugo
- sudo pip install s3cmd
script:
- hugo
- s3cmd --acl-public --delete-removed --add-header=Cache-Control:max-age=3600 --no-progress sync public/ s3://blog.vvatanabe.com
notifications:
  email:
    on_failure: always