languageCode = "en-us"
title = "Diary"
baseURL = "https://vvatanabe.github.io/diary"
theme = "hugo-black-and-light-theme"
canonifyurls = true
publishDir = "docs"
disqusShortname = "vvatanabe"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[permalinks]
  post = "post/:year/:month/:day/:title/"

[params]
  sitename = "Diary"
  author = "Yuichi Watanabe"

[[menu.main]]
    name = "About"
    url  = "/post/2017/02/22/about-this-diary/"
    Weight = 1
[[menu.main]]
    name = "Categories"
    url  = "/categories/"
    Weight = 101
[[menu.main]]
    name = "Tags"
    url  = "/tags/"
    Weight = 102
[[menu.main]]
    name = "Facebook"
    url  = "https://www.facebook.com/profile.php?id=100006205456811"
    Weight = 201
[[menu.main]]
    name = "Github"
    url  = "https://github.com/vvatanabe"
    Weight = 201
[[menu.main]]
    name = "Twitter"
    url  = "https://twitter.com/vvatanabe_ja"
    Weight = 203