languageCode = "en-us"
title = "blog.vvatanabe.com"
baseURL = "https://blog.vvatanabe.com"
theme = "hugo-black-and-light-theme"
canonifyurls = true
disqusShortname = "vvatanabe"
googleAnalytics = "UA-93081819-1"

[taxonomies]
category = "categories"
tag = "tags"

[permalinks]
  post = "post/:year/:month/:day/:title/"

[params]
  sitename = "blog.vvatanabe.com"
  symbol_icon = "/mustache.svg"
  author = "Yuichi Watanabe"
  eyecatch = "/images/default-eyecatch.png"
  description = "The contents are usually technology, work, Japanese sake, sumo wrestling, music, daily life activities and so on. If I make mistakes in my English, please pardon me. If you are an engineer, would you give me a pull request on Github please? https://github.com/vvatanabe/blog.vvatanabe.com"

[params.share]
  facebook_app_id = 964534250348303

[params.social]
  Facebook = "vvatanabe.ja"
  Github = "vvatanabe"
  Twitter = "vvatanabe_ja"
  Soundcloud = "vvatanabe"
  Email = "yuichi.watanabe.ja@gmail.com"

[[menu.main]]
    name = "About"
    url  = "/about/"
    Weight = 1
[[menu.main]]
    name = "Categories"
    url  = "/categories/"
    Weight = 2
[[menu.main]]
    name = "Tags"
    url  = "/tags/"
    Weight = 3