languageCode = "en-us"
title = "blog.vvatanabe.com"
baseURL = "https://blog.vvatanabe.com"
theme = "hugo-black-and-light-theme"
canonifyurls = true
disqusShortname = "vvatanabe"

[taxonomies]
category = "categories"
tag = "tags"

[permalinks]
  post = "post/:year/:month/:day/:title/"

[params]
  sitename = "blog.vvatanabe.com"
  author = "Yuichi Watanabe"

[params.social]
  Facebook = "vvatanabe.ja"
  Github = "vvatanabe"
  Twitter = "vvatanabe_ja"
  Soundcloud = "vvatanabe"
  Email = "yuichi.watanabe.ja@gmail.com"

[[menu.main]]
    name = "About"
    url  = "/about/"
    Weight = 1
[[menu.main]]
    name = "Categories"
    url  = "/categories/"
    Weight = 2
[[menu.main]]
    name = "Tags"
    url  = "/tags/"
    Weight = 3